### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by am-kaiser** [AtMoDat/atmodat_standard_checker#20]

**Comment by am-kaiser** [comment]
The used code has the following licenses:

•	Cc-yaml: BSD 3-Clause License
•	Compliance-check-lib: BSD 3-Clause License
•	Compliance-checker: Apache License, Version 2.0, January 2004
•	Cf-checker: BSD Licence, Copyright (c) 2010, University of Reading

According to this page: [https://dwheeler.com/essays/floss-license-slide.html](https://dwheeler.com/essays/floss-license-slide.html) I think we can use the Apache 2.0 license for our code. @jkretz do you agree?

**Comment by jkretz** [comment]
@am-kaiser I am absolutely no expert in that regard but according to the flow chart you provided, we probably need to use the Apache license as it is used in compliance-checker
